[package]
name = "foc-search-server"
version = "0.1.0"
authors = ["Mariano Guerra <mariano@marianoguerra.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sonic_client = "0.1.2"
